### ISSUE TITLE
Nonexistant entity in MD still redirects to "saved" IDP

### ISSUE THREAD

**Issue by simmel** [IdentityPython/pyFF#113]
If you have "saved" which IDP you're authenticating with using "Login and use Forever" you get redirected to that IDP even though the SP/entityID you're trying to login with doesn't exist in the metadata that pyFF has. CherryPy (I guess) is showing an 404 when you haven't set an IDP to use forever.

I suspect the offending code is here and that it somehow should check if we're an 404:
https://github.com/leifj/pyFF/blob/063f0dea00374c8636046b2c0fdba2b837e721e3/src/pyff/site/static/js/pyff.js#L77-L105

**Comment by leifj** [comment]
The code gets called from _autoselect() which tries to get rid of "stale" IdPs. A couple of questions: Can you reproduce the problem - i.e do you have an entityID of an IdP and an aggregator where it is definitely gone from that I can use for testing?

**Comment by simmel** [comment]
On Fri, 2017-10-13 at 04:51:14 -0700, Leif Johansson wrote:
> The code gets called from _autoselect() which tries to get rid of "stale" IdPs. A couple of questions:
> Can you reproduce the problem - i.e do you have an entityID of an IdP 
and an aggregator where it is definitely gone from that I can use for 
testing?

Sure, use <https://masv3971-lab-srv02.it.su.se>

It's not in SWAMID but our IDP recognizes it.

BR,
- Simon

**Comment by simmel** [comment]
Any news @leifj ?

**Comment by leifj** [comment]
Sorry for the delay in responding. This code was deprecated in favor of the new discovery service over at theidentityselector/thiss-js. I suggest you switch to it asap if you haven't already. The code this issue is referring to will soon be removed from pyFF.
