### ISSUE TITLE
Caching timeouts

### ISSUE THREAD

**Issue by mrvanes** [IdentityPython/pyFF#116]
We're regulary (but not allways) seeing long delays on loading the WAYF and suspect these logs are related (correlated by timing).
```
Nov  2 09:51:01 proxy2 pyffd[39159]: INFO:cherrypy.error.140361733912592:[02/Nov/2017:09:51:01] TOOLS.CACHING Waiting up to 30 seconds
Nov  2 09:51:31 proxy2 pyffd[39159]: [02/Nov/2017:09:51:31] TOOLS.CACHING Timed out
...
Nov  2 09:51:31 proxy2 pyffd[39159]: INFO:cherrypy.error.140361733912592:[02/Nov/2017:09:51:31] TOOLS.CACHING Waiting up to 30 seconds
Nov  2 09:52:01 proxy2 pyffd[39159]: [02/Nov/2017:09:52:01] TOOLS.CACHING Timed out
...
Nov  2 09:52:01 proxy2 pyffd[39159]: INFO:cherrypy.error.140361733912592:[02/Nov/2017:09:52:01] TOOLS.CACHING Waiting up to 30 seconds
Nov  2 09:52:31 proxy2 pyffd[39159]: [02/Nov/2017:09:52:31] TOOLS.CACHING Timed out
```
One of the metadata sources is a locally cached, transformed eduGAIN set so the metadata set is quite big, but as far as I understand the rest of the logging, that file is regularly collected and parsed without problems.

Can anyone shed a light on the above logging lines and tell what fails while waiting for the WAYF to show up?

**Comment by mrvanes** [comment]
So, I've been able to track this down to cherrypy's AntiStampedeCache class. As far as I understand it, cherrypy is used to serve pyFF pages and has nothing to do with metadata handling, am I right? Does this mean it's safe to conclude we're looking at a pyFF server caching problem either from code or system problem (IO/Memory?) or cherrypy bug?

**Comment by leifj** [comment]
Skickat från min iPhone

> 3 nov. 2017 kl. 15:40 skrev Martin <notifications@github.com>:
> 
> So, I've been able to track this down to cherrypy's AntiStampedeCache class. As far as I understand it, cherrypy is used to serve pyFF pages and has nothing to do with metadata handling, am I right? Does this mean it's safe to conclude we're looking at a pyFF server caching problem either from code or system problem (IO/Memory?) or cherrypy bug?
> 
I suspect neither. Pyff won’t serve up the DS until it had gone through a full cycle of metadata updates. Tis may take time and while waiting the cache layer will just fail like this. I suspect your metadata loads are just slow....

**Comment by leifj** [comment]
Skickat från min iPhone

> 3 nov. 2017 kl. 16:16 skrev Martin <notifications@github.com>:
> 
> So, you say this is a coincidence on requesting the WAYF while metadata is being processed/renewed at the same time? Or is the metadata refresh caused by requesting the WAYF? Could the stale metadata be used while new metadata is refreshed to prevent these massive delays? We're still in test/pilot but this would be a showstopper in a production environment.
> 

I have been looking at ways to refactor the store layer to deal with this issue but in production you would most likely use an active-active or active-passive HA setup right? 

At least that is what I do so then startup time shouldn’t really become an issue.

However I would investigate if there are other possible explanations... normally loading & processing edugain only takes a few seconds...

There is also the redis store... less tested than the in-memory store but should let to startup faster. Should be treated as experimental.

**Comment by mrvanes** [comment]
This is not a startup problem. The server has been running for days. The delays are intermittently when we do an end-to-end test via satosa, using pyFF as our disco server.
And, I noticed this: the first failing role/idp.ds request is at Nov  2 09:51:01. It then times out two times 30 seconds as can be seen above and then only at Nov  2 09:52:31 (a full minute later) the xhr request for the {http:/pyff.io/role}idp.json is requested. Why would idp.ds wait so long before firing the json xhr request?

**Comment by leifj** [comment]
Skickat från min iPhone

> 3 nov. 2017 kl. 16:30 skrev Martin <notifications@github.com>:
> 
> This is not a startup problem. The server has been running for days. The delays are intermittently when we do an end-to-end test via satosa, using pyFF as our disco server.
> 
Thats strange. Does it correlate with the update run?

You may want to try turning off cache (-C) and add an external cache server (eg varnish) ...


> And, I noticed this: the first failing role/idp.ds request is at Nov 2 09:51:01. It then times out two times 30 seconds as can be seen above and then only at Nov 2 09:52:31 (a full minute later) the xhr request for the {http:/pyff.io/role}idp.json is requested. Why would idp.ds wait so long before firing the json xhr request?
> 

Also strange...The frontend is getting overhauled!

**Comment by mrvanes** [comment]
The last update run was approximately 7 minutes before the DS request that times out:
```
Nov  2 09:44:52 proxy2 pyffd[39159]: DEBUG:cherrypy.error.140361733912592:[02/Nov/2017:09:44:52]  update produced new repository with 535 entities
Nov  2 09:51:01 proxy2 gunicorn[37813]: [2017-11-02 09:51:01] [DEBUG]: read request data: {'RelayState': 'https://******/registry/auth/login', 'Signature': 'X7xbAmD9R8fBFieoWeTd8QyEVysiasYpzk9W4XyuQ12fQtDzY4KiUtZc/OM0l

**Comment by mrvanes** [comment]
Was fixed by cherrypy and not relevant anymore for pyFF wsgi
