### ISSUE TITLE
Double slashes in ATTR constants get stripped in cherrypy before EncodingDispatcher

### ISSUE THREAD

**Issue by mrvanes** [IdentityPython/pyFF#117]
I was stumped by the DS getting a 404 on the boe-browser.min.js xhr request for metadata/%7Bhttp://pyff.io/domain%7Dexample.org+%7Bhttp://pyff.io/role%7Didp.json where the normal /role/idp.json page would return expected results. It turns out cherrypy strips all double occurences of slashes from the path even before EncodingDispatcher can get it's hands on path_info. This resulted in an index lookup for http:/pyff.io/domain=example.org and http:/pyff.io/role=idp which never returns any result (mind the single slashes in the protocol prefix!)

The easiest work-around was to remove all occurences of double slashes in ATTR definition in constants.py.

This results in expected behaviour of the normal metadata interface behaviour combined with sane results from queries like /metadata/{http://pyff.io/role}idp.json.
It still results in 404 for queries that result in empty intersection, but that's expected.

I was not able to patch boe-browser.min.js for the offending request containing the double slashes, because of the minimized character of this file.

**Comment by mrvanes** [comment]
Hmm... this breaks the idp.s DS query, because there, the ATTR url is hidden in a entity_filter request parameter and thus left intact by cherrypy. Back to the drawing board.

**Comment by mrvanes** [comment]
The query that now breaks is the home (based on SP domain) IdP selector, as far as I understand the code.

**Comment by mrvanes** [comment]
It's this code that wreaks havoc, and it's called before EncodingDispatcher
https://github.com/cherrypy/cherrypy/blob/294836c1079496107930f653e3bd8d6ce017f2f2/cherrypy/lib/httputil.py#L47

**Comment by leifj** [comment]
OK but thats part of cherrypy... I'm not sure if this is a bug or not... and if so how is it a bug in pyFF?

**Comment by mrvanes** [comment]
Well, like I said in the first post: boe-browser.min.js does an xhr request to find home realm from an intersection of a domain=<sp-domain>+role=idp query. The problem is this query is hidden in the path:

```https://<server>/metadata/%7Bhttp://pyff.io/domain%7Dexample.org+%7Bhttp://pyff.io/role%7Didp.json```

Part of this query in the path string are the pyFF attributes "http://pyff.io/domain" and "http://pyff.io/role".
That is impossible, by virtue of the cherrypy double slash consolidation, because pyFF only sees the following path_info:

```metadata/{http:/pyff.io/domain}example.org+{http:/pyff.io/role}idp.json```

Which will never match anything.

**Comment by leifj** [comment]
Skickat från min iPhone

> 6 nov. 2017 kl. 21:45 skrev Martin <notifications@github.com>:
> 
> Well, like I said in the first post: boe-browser.min.js does an xhr request to find home realm from an intersection of a domain=+role=idp query. The problem is this query is hidden in the path:
> 
> https://<server>/metadata/%7Bhttp://pyff.io/domain%7Dexample.org+%7Bhttp://pyff.io/role%7Didp.json
> 
> Part of this query in the path string are the pyFF attributes "http://pyff.io/domain" and "http://pyff.io/role".
> That is impossible, by virtue of the cherrypy double slash consolidation, because pyFF only sees the following path_info:
> 
> metadata/{http:/pyff.io/domain}example.org+{http:/pyff.io/role}idp.json
> 
> Which will never match anything.
> 

I see. I need to think about this.

**Comment by mrvanes** [comment]
Well, I couldn't care less about the home realm discovery, that's not my point. My advice would be to step away from the overly complicated pyFF attribute notation, because they're obviously doing more wrong than good and I assume it would be hard to find all occurences where this hurts in the code. Just change then to pyff_domain and pyff_role, find replace in the code and your're done ;)

**Comment by leifj** [comment]
Skickat från min iPhone

> 7 nov. 2017 kl. 15:55 skrev Martin <notifications@github.com>:
> 
> Well, I couldn't care less about the home realm discovery, that's not my point. My advice would be to step away from the overly complicated pyFF attribute notation, because they're obviously doing more wrong than good and I assume it would be hard to find all occurences where this hurts in the code. Just change then to pyff_domain and pyff_role, find replace in the code and your're done ;)
> 

I must admit the thought had crossed my mind...

**Comment by mrvanes** [comment]
Here's a patch that fixes the problem (for me). It includes extra debug statements and uncomment of existing to prove proper filtering. the home-realm xhr request that triggered a 404 now returns a valid list of IdP's. This patch does *not* fix test/data/mdx/mdx.fd and examples/mdx.fd
```
Nov 10 10:02:52 proxy1 pyffd[36754]: [10/Nov/2017:10:02:52]  calling store lookup {pyff-domain}test.example.org;example.org;example.org;example.org+{pyff-role}idp
Nov 10 10:02:52 proxy1 pyffd[36754]: [10/Nov/2017:10:02:52]  _lookup key '{pyff-domain}test.example.org;example.org;example.org;example.org+{pyff-role}idp'
Nov 10 10:02:52 proxy1 pyffd[36754]: [10/Nov/2017:10:02:52]  lookup intersection of '{pyff-domain}test.example.org;example.org;example.org;example.org and {pyff-role}idp'
Nov 10 10:02:52 proxy1 pyffd[36754]: [10/Nov/2017:10:02:52]  _lookup key '{pyff-domain}test.example.org;example.org;example.org;example.org'
Nov 10 10:02:52 proxy1 pyffd[36754]: [10/Nov/2017:10:02:52]  ... adding pyff-domain=test.example.org
Nov 10 10:02:52 proxy1 pyffd[36754]: [10/Nov/2017:10:02:52]  a: pyff-domain, v: test.example.org
Nov 10 10:02:52 proxy1 pyffd[36754]: [10/Nov/2017:10:02:52]  ... adding pyff-domain=example.org
Nov 10 10:02:52 proxy1 pyffd[36754]: [10/Nov/2017:10:02:52]  a: pyff-domain, v: example.org
Nov 10 10:02:52 proxy1 pyffd[36754]: [10/Nov/2017:10:02:52]  ... adding pyff-domain=example.org
Nov 10 10:02:52 proxy1 pyffd[36754]: [10/Nov/2017:10:02:52]  a: pyff-domain, v: example.org
Nov 10 10:02:52 proxy1 pyffd[36754]: [10/Nov/2017:10:02:52]  ... adding pyff-domain=example.org
Nov 10 10:02:52 proxy1 pyffd[36754]: [10/Nov/2017:10:02:52]  a: pyff-domain, v: example.org
Nov 10 10:02:52 proxy1 pyffd[36754]: [10/Nov/2017:10:02:52]  _lookup key '{pyff-role}idp'
Nov 10 10:02:52 proxy1 pyffd[36754]: [10/Nov/2017:10:02:52]  ... adding pyff-role=idp
Nov 10 10:02:52 proxy1 pyffd[36754]: [10/Nov/2017:10:02:52]  a: pyff-role, v: idp
Nov 10 10:02:52 proxy1 pyffd[36754]: [10/Nov/2017:10:02:52]  selecting 2 entities before validation
```
[pyff-attributes.txt](https://github.com/leifj/pyFF/files/1460951/pyff-attributes.txt)

**Comment by leifj** [comment]
Ok I will probably do this a bit differently in the branch where I’m refactoring discovery. Thank you for your work on this!

Skickat från min iPhone

**Comment by leifj** [comment]
I'm going to close this since I'm about to drop cherrypy.
