### ISSUE TITLE
Question: is there a way to keep the output order of entities stable accross runs?

### ISSUE THREAD

**Issue by andmor-** [IdentityPython/pyFF#130]
When using the current master, pyFF outputs the entities in a random order.
We have some diff tools that are not yet prepared for this and although they will be fixed, I would like to know if there is a known way to keep the output order across runs (using same input data), as it happened with previous versions up to 1d032fe6955ac2661a355f12b937b4984a9295dc

**Comment by leifj** [comment]
That would require implementing a sort-pipe - probably based on entityID lexical order. That would not be too hard! I would definitely welcome a pull-request for that. The way python handles hash-tables is the reason for the indeterminate order.

**Comment by andmor-** [comment]
Thank you. 
My python knowledge is fairly limited but I will give it a try when I find some time. Any advice will be welcome.
