### ISSUE TITLE
[DS Feature] jquery widget to support more list mechanisms

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/pyFF#167]
Having read the wiki related page [here](https://github.com/IdentityPython/pyFF/wiki/Discovery-Service) and knowing about the [TheIdentitySelector](https://github.com/TheIdentitySelector) goals, I'm wondering about the need to develop a Search jquery widget with an ajax scrollable list.

This would follow the [Future development](https://github.com/IdentityPython/pyFF/wiki/Discovery-Service#future-development) about pyFF.

I would like to do something reusable, is there any community orientation to talk on?

## Code Version
I'd reuse the static html currently in this master branch to export an independent static site. 
If you have some suggestions about the most updated branch to take from, please tell me.

## Expected Behavior
A static web site that use [ds-client.js](https://github.com/TheIdentitySelector/thiss-ds-js) to query pyFF's DiscoveryService.

**Comment by peppelinux** [comment]
Something like https://select2.org

**Comment by leifj** [comment]
> Having read the wiki related page here and knowing about the TheIdentitySelector goals, I'm wondering about the need to develop a Search jquery widget with an ajax scrollable list.
> 

In fact such a thing already exists & its based on bts-listfilter (which is better at mobile than select2 which I used to rely on). 

The plugin currently lives inside the thiss-js repo but will be lifted out very soon and published to npm etc. The live beta at use.thiss.io is based on this plugin.

**Comment by leifj** [comment]
I'm going to close this issue since it is referring to code that is about to be deprecated and removed from pyFF. Work on the UX has moved to mdq-browser and theidentityselector/thiss-js for the admin ui and discovery service respectively.
