### ISSUE TITLE
ImportError: No module named _collections_abc

### ISSUE THREAD

**Issue by guillomovitch** [IdentityPython/pyFF#169]
I'm trying to run pyff on Centos 7 x86_64, using python 2.. I've satisfied all required dependencies, according to the setup.py file, using official Centos packages and self-packaged ones. However, I now run into the following error, while trying to run pyff:

```
[rousse@buildhost]$ pyff
Traceback (most recent call last):
  File "/usr/bin/pyff", line 11, in <module>
    load_entry_point('pyFF==1.0.1', 'console_scripts', 'pyff')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/pyff/md.py", line 14, in <module>
    from .samlmd import MDRepository
  File "/usr/lib/python2.7/site-packages/pyff/samlmd.py", line 2, in <module>
    from .utils import parse_xml, check_signature, root, validate_document, xml_error, \
  File "/usr/lib/python2.7/site-packages/pyff/utils.py", line 47, in <module>
    from _collections_abc import MutableMapping
ImportError: No module named _collections_abc
```

'_collections_abc' doesn't seem to the be name of any python distribution, according to pypi.
I'm probably hitting a version issue in one of the dependency, but I'm unable to figure which one.

**Comment by leifj** [comment]
Python 2 is no longer supported. You must use 3.5 or later.

**Comment by guillomovitch** [comment]
This information would benefit from being exposed more clearly, because I couldn't find any mention of it anywhere, neither on pipy metadata, neither in shipped documentation files.

**Comment by leifj** [comment]
There is mention of this in the roadmap document on the wiki.

**Comment by guillomovitch** [comment]
That may be true, but actually I have no clue which wiki you are refering to. The only three documentation source I know are the URLs mentioned in the top-level README.rst file, ie:
-    http://github.com/IdentityPython/pyFF
-    http://pypi.python.org/pypi/pyFF
-    http://packages.python.org/pyFF

The latest one being obviously obsolete, I guess the simplest fix would be to replace it by a link for this wiki.

**Comment by leifj** [comment]
The wiki right here at github... but also the documentation on pypi sais that you need a reasonably modern python and 2.x is no longer that...
