### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by leifj** [IdentityPython/pyFF#17]
in DS:
- pick images and other elements based on browser language prefs
- i18n for static text elements

**Comment by rhoerbe** [comment]
DIP Discovery service: If there is only a non-English language element it should be taken as default, such as a <mdui:DisplayName xml:lang="de">,

**Comment by leifj** [comment]
I'm going to close this issue since it is referring to code that is about to be deprecated and removed from pyFF. Work on the UX has moved to mdq-browser and theidentityselector/thiss-js for the admin ui and discovery service respectively.
