### ISSUE TITLE
Support for running external scripts as input

### ISSUE THREAD

**Issue by guillomovitch** [IdentityPython/pyFF#186]
The current _load_ builtin only accepts remote URLs, local files or directory, and doesn't allow to run an external script. A workaround is to delegate this execution to a web server, turning those command-line scripts into CGI scripts, of course, but I would be more flexible to support it directly from pyff.

I had a quick look at the code, in order to evaluate how easy it would be to plug support in the current _load_ pipe, for instance with another handler for a custom URL scheme such as exe://, however it seems to closely tied to python requests library to support such hack, and would probably easier to implement as an independent pipe.

**Comment by leifj** [comment]
Yeah so load delegates processing to a thread pool that uses python requests to fetch both remote and local files. Shoehorning calling scripts into this ... would be painful. Probably easier to spin off a background thread that looks like a webserver if you want to use load..
