### ISSUE TITLE
MDQ response for non-standard request by identifier

### ISSUE THREAD

**Issue by skoranda** [IdentityPython/pyFF#202]
The current base Metadata Query Protocol draft is at

https://www.ietf.org/archive/id/draft-young-md-query-13.txt

The issue is how should pyFF respond to a query like

`curl -X GET -H 'Accpet: application/json' http://localhost/entities%7Bsha1%7D0dc7abb7d11e8e4fd505ad7499ae5971e266c4fd.json`

Here the entityID is 

`urn:mace:incommon:uchicago.edu`

and the sha1 hash of that is

`0dc7abb7d11e8e4fd505ad7499ae5971e266c4fd`

So the unencoded entity identifier is

`{sha1}0dc7abb7d11e8e4fd505ad7499ae5971e266c4fd`

Note that there is no slash after `entities` in the query above.

Currently pyFF version 1.1.4 returns a JSON list of metadata for all the entities it knows about, ignoring the hashed identity identifier. 

When a slash is included between `entities` and the encoded hash then the metadata for the single entity is returned.

3.2.1 "Request by Identifier" of the base protocol requires a slash after `entities`, so the query above  is strictly non-conformant. 

But since pyFF tries to be forgiving, should it respond to the above query with the metadata for the single entity? After all, the query isn't ambiguous since it is clear that everything after `entities` is part of the (hashed) identifier.

3.2.2 explains that the metadata query request for all entities should end with `entities`, so if there is more appended after `entities` should pyFF instead fail since the query is not compliant?

**Comment by leifj** [comment]
thx! is this pyffd (cherrypy) or the flask version?

**Comment by skoranda** [comment]
Flask version.

**Comment by leifj** [comment]
Actually - correct that. Having looked at that issue for a bit I'm pretty firmly in the "no-fix" corner now. As you say this is clearly a bad request and even though it may seem to be unambiguous we can't rule out somebody creating an entityID that hashes to that particular sequence of strings. The result would be a bitch to track down for the sorry sod tasked with maintaining that particular pyFF instance and I'm frankly worried what they would do once they found out.
