### ISSUE TITLE
distorted logo

### ISSUE THREAD

**Issue by nullaegy** [IdentityPython/pyFF#204]
Select your already saved organization.
The logo is there, but if it's not a square 1:1 logo then it will distort it.

I think it would be better if you skip min-height in the crop img tag and only use min-width:
https://github.com/IdentityPython/pyFF/blob/master/src/pyff/site/static/css/icon.css#L29

```
.crop img {
    display: block;
    min-width: 100%;
    /* min-height: 100%; */
    margin: auto;
    position: absolute;
    top: -100%;
    right: -100%;
    bottom: -100%;
    left: -100%;
```
![image](https://user-images.githubusercontent.com/34267836/106577151-4da57980-653e-11eb-958e-8076c676016b.png)

**Comment by leifj** [comment]
thats a good suggestion... however this relates to the discovery feature in pyFF which has been deprecated in favor of TheIdentitySelector/thiss-js where most of this technology landed. I believe we wound up not using icons in the same way in that project but pls do check!

**Comment by nullaegy** [comment]
I kinda like it if there is a logo to show and this way you can easily check the proper item. User Experience is much better this way. But that's another topic to debate. Thank you if you consider changing the code in the meantime.

**Comment by leifj** [comment]
The UX studies we did in the ra21 project suggests logos confuse more than they help actually. I'll definitely drop in the change if you give me a PR tho! I agree that if you have logos you should do it right.
