### ISSUE TITLE
mousless organization selection

### ISSUE THREAD

**Issue by nullaegy** [IdentityPython/pyFF#206]
When you land on the page you can already start to search for your desired organization. But you cannot select it without moving the mouse to the proper entry.

Please make the organization selection usable without a mouse.
For example: type text --> hit [Enter] --> select top entry.
Optional: Add a color-coding or indenting the currently pre-selected entry.

**Comment by leifj** [comment]
A PR would be well received! Other than that the same comment about deprecation applies here too. The Admin UX is now a separate project called mdq-browser.

**Comment by leifj** [comment]
Gona close this issue since the code is about to be deprecated.
