### ISSUE TITLE
Stylesheets and fork

### ISSUE THREAD

**Issue by majagw** [IdentityPython/pyFF#209]
I have a pipe like that:
- load:
  - ...
  - ...
- select:
- xslt:
    stylesheet: pubinfo.xsl
    publisher: http://mds.edugain.org/
- fork:
  - sign:
      key: signer-v1-1/edugainsigner.key
      cert: signer-v1-1/edugainsigner-v1-1.pem
   - publish: /srv/www/MDSfeed/edugain-v1-1.xml
- fork:
  - sign:
      key: signer-v1/edugainsigner.key
      cert: signer-v1/edugainsigner-v1.pem
  - publish: /srv/www/MDSfeed/edugain-v1.xml

It fails with pyff v. 1.1.5:
ERROR:pyff.pipes:'lxml.etree._XSLTResultTree' object has no attribute 'get'
ERROR:root:'lxml.etree._XSLTResultTree' object has no attribute 'get'

pyff version 1.1.2dev0 processes such a pipe smootly.

When I move xslt command to each fork
- fork:
   - xslt:
       stylesheet: pubinfo.xsl
       publisher: http://mds.edugain.org/
   - sign:
      key: signer-v1-1/edugainsigner.key
      cert: signer-v1-1/edugainsigner-v1-1.pem
   - publish: /srv/www/MDSfeed/edugain-v1-1.xml
- fork:
   - xslt:
       stylesheet: pubinfo.xsl
       publisher: http://mds.edugain.org/
   - sign:
      key: signer-v1/edugainsigner.key
      cert: signer-v1/edugainsigner-v1.pem
   - publish: /srv/www/MDSfeed/edugain-v1.xml

then pyff v. 1.1.5 ends successfully.
Unfortunately moving pubinfo.xsl to another fork makes that creationInstantavalue  changes when an active document contains a lot of entities (like the eduGAIN feed) and as a result signature value is different.

I attach the debug log for pipe with
- load:
    - http://localhost/MDSfeed/PIONIER-ID.xml as PIONIER-ID
    - http://localhost/MDSfeed/EDUGATE.xml as EDUGATE
[error.log](https://github.com/IdentityPython/pyFF/files/6189008/error.log)

**Comment by leifj** [comment]
I suspect there is a missing call to root() somewhere - I'll investigate further.

**Comment by leifj** [comment]
Can you try the master branch now?
