### ISSUE TITLE
When filtering by entity type, I get a response that includes all entities

### ISSUE THREAD

**Issue by alejandro-perez** [IdentityPython/pyFF#243]
When filtering by entity type, when I try to get on entity's JSON metadata, I get a response that includes all entities instead.

However, search works fine, and returns the matching entities after filter has been applied.

## Code Version

2.0.0 (docker image)

## Expected Behavior

Only the entity matching the SHA1 hash is returned.

## Current Behavior

All entities are returned (~5k)

## Steps to Reproduce

1. Use the following config
```
- when update:
    - load:
        - http://metadata.ukfederation.org.uk/ukfederation-metadata.xml
    - break
- when request:
    - select:
    - pipe:
        - when accept application/json:
            - select:
              - '!//md:EntityDescriptor[md:IDPSSODescriptor]'
            - discojson
            - emit application/json:
            - break
```
2. Try to get an entity's JSON metadata (as expected by thiss-js)
```
curl "http://localhost:8080/%7Bentities/%7Bsha1%7D573116c096bd85296da6c0fd921b9f36dc4c3805.json" -H "Accept: application/json"
```
3. Get a full list of 5k entities
4. By disabling the select filter in step 1, the results frm step 2 are just the expected ones:4
```
[{"title": "UM - University of Murcia", "descr": "The Identity Provider of University of Murcia", "title_langs": {"es": "UM - Universidad de Murcia", "en": "UM - University of Murcia"}, "descr_langs": {"es": "El proveedor de identidad de la Universidad de Murcia", "en": "The Identity Provider of University of Murcia"}, "auth": "saml", "entity_id": "https://www.rediris.es/sir/umidp", "entityID": "https://www.rediris.es/sir/umidp", "type": "idp", "hidden": "false", "scope": "um.es", "domain": "um.es", "name_tag": "UM", "entity_icon_url": {"url": "https://img.sir2.rediris.es/200px-201a27c316f210f42657d783f2ae8fa0.png", "width": "200", "height": "53"}, "keywords": "um,murcia"}]
```

**Comment by leifj** [comment]
The implicit select is essentially "overwritten" by the explicit select in the when clause so returning all 5k entities is actually the correct behavior in that case.

**Comment by alejandro-perez** [comment]
Thanks @leifj . Is there any way in which I can get the functionality I want, where searchs only return IDPs, while grabbing one entity's metadata can return any from the loaded feed? (this is how seamlessaccess.org works, but I couldn't find how to replicate).

Sorry I ask here, but I haven't seen anything in the docs or examples that shed any light on this.

**Comment by alejandro-perez** [comment]
To mimic the example above:
```
curl "https://md.seamlessaccess.org/entities/%7Bsha1%7Dd6cad1541a6653fa308955d7341b7171bc970f09.json" -H "Accept: application/json"
{"title":"DevTeam Test RPi Box","descr":"DevTeam's Test RPi Box","title_langs":{"en":"DevTeam Test RPi Box"},"descr_langs":{"en":"DevTeam's Test RPi Box"},"auth":"saml","entity_id":"https://rpi.dev.ukfederation.org.uk/shibboleth","entityID":"https://rpi.dev.ukfederation.org.uk/shibboleth","type":"sp","id":"{sha1}d6cad1541a6653fa308955d7341b7171bc970f09"}
```

But:
```
curl "https://md.seamlessaccess.org/entities/?query=rpi" -H "Accept: application/json" 
[{"title":"Rensselaer Polytechnic Institute","descr":"http://www.rpi.edu/","title_langs":{"en":"Rensselaer Polytechnic Institute"},"descr_langs":{"en":"http://www.rpi.edu/"},"auth":"saml","entity_id":"https://shib-idp.rpi.edu/idp/shibboleth","entityID":"https://shib-idp.rpi.edu/idp/shibboleth","type":"idp","hidden":"false","scope":"rpi.edu","domain":"rpi.edu","name_tag":"RPI","entity_icon_url":{"url":"https://scer.rpi.edu/sites/default/files/logo-without-tag.jpg","width":"673","height":"175"},"privacy_statement_url":"http://scer.rpi.edu/privacypolicy","id":"{sha1}549b3f2200a9f8c5d11808ff74931d68be4d32f8"}]
```

**Comment by leifj** [comment]
We don't filter in SA actually but you can achieve the effect you want by adding a filter step after the select - the API docs has an example but doing something like this should work:
```yaml
- select:
- filter:
     - "!//md:EntityDescriptor[md:IDPSSODescriptor]"
```

**Comment by alejandro-perez** [comment]
From my example above against SA, you can see how results from the `/entities/?query=XXX` endpoint do filter, since otherwise `DevTeam's Test RPi Box` would have been included in the results.

In any case, I'll try using filter. Where can I find the API docs? https://pyff.readthedocs.io/en/latest/ do not mention anything about filter. Thanks!

**Comment by alejandro-perez** [comment]
Also, if I use filter, the SP details are not returned (cause, it's an SP). SA does not show this behaviour.

Using the following link, you can see how SP's details are fetched (top left corner shows display name), while still the search does not return any SP (only IDPs).

https://service.seamlessaccess.org/ds/?entityID=https%3A%2F%2Frpi.dev.ukfederation.org.uk%2Fshibboleth&return=https%3A%2F%2Falexrpi.ddns.net%3A9443%2FShibboleth.sso%2FLogin%3FSAMLDS%3D1%26target%3Dss%253Amem%253A65d9ecc802bd1a9cdc618855df00dd9a2e4302888cee6d3f502293f2b3cef70d

**Comment by leifj** [comment]
Search is not handled via pipelines in pyFF. The filter clause is documented in the source but maybe readthedocs isn't exposing all the API docs. I will look into that.

**Comment by leifj** [comment]
> Also, if I use filter, the SP details are not returned (cause, it's an SP). SA does not show this behaviour.

As I said above, SA doesn't do filtering - both SPs and IdPs are included in the metadata feed from SA.

**Comment by alejandro-perez** [comment]
> As I said above, SA doesn't do filtering - both SPs and IdPs are included in the metadata feed from SA however not all SPs are included in SA because SA only looks at edugain and a few other federation feeds currently so your test box might not be included in one of those feeds. This could be the reason you're not seeing it.

I'm not sure about that. The name of the test box is rendered properly on the top-left corner (cause it's the requesting SP), but you cannot find it using the search.

Somehow, even though SA is including all entities (because you can see how the SP name is displayed correctly), it manages to filter SPs out of hte search results. Whether that is done at the pyFF level or thiss.io I do not know.

**Comment by alejandro-perez** [comment]
> Search is not handled via pipelines in pyFF. The filter clause is documented in the source but maybe readthedocs isn't exposing all the API docs. I will look into that.

Thanks that'll be useful
