### ISSUE TITLE
IDP disco ?return vs. <idpdisc:DiscoveryResponse>

### ISSUE THREAD

**Issue by rhoerbe** [IdentityPython/pyFF#46]
When the SP announces the response URI in metadata, and does not send the return parameter, mdx.py does not return the reponse.

**Comment by leifj** [comment]
I'm going to close this issue since it is referring to code that is about to be deprecated and removed from pyFF. Work on the UX has moved to mdq-browser and theidentityselector/thiss-js for the admin ui and discovery service respectively.
