### ISSUE TITLE
Allow configuration of url-path

### ISSUE THREAD

**Issue by remold** [IdentityPython/pyFF#60]
To add pyFF as a service 'on top' of a existing website we like to use apache mod-proxy. Using mod-proxy we need to rewrite the html-code since there is already content in the docroot of the webserver.

When pyFF can serve webpages when accessed via http://<servername>/<path>/\* (instead of http://<servername>/\* no rewrite is necessary.

We know there are other options, but those are more complex and require more configuration.

**Comment by leifj** [comment]
Pull request?

**Comment by leifj** [comment]
I'm going to close this issue since pyFF is about to drop cherrypy in favor of flask/pygments making it much easier to integrate the pyFF api into existing sites.
