### ISSUE TITLE
Redirects twice when sending discovery response back to the SP

### ISSUE THREAD

**Issue by zamzterz** [IdentityPython/pyFF#76]
After selecting an IdP, using the "Proceed to Login" or "Login and Use Forever->Use this time only" option results in two redirects with the discovery response back to the SP when using Firefox (43.0.4).
![pyff_two_redirects](https://cloud.githubusercontent.com/assets/1183700/12173339/894c07f8-b556-11e5-8eb7-515e25282337.png)

Using "Login and Use Forever->Yes I am Sure - Use Forever" only issues one redirect.
![pyff_one_redirect](https://cloud.githubusercontent.com/assets/1183700/12173338/894aa534-b556-11e5-9e44-801e5dabbccf.png)

**Comment by leifj** [comment]
Skickat från min iPhone

> 7 jan. 2016 kl. 15:52 skrev Rebecka Gulliksson <notifications@github.com>:
> 
> After selecting an IdP, using the "Proceed to Login" or "Login and Use Forever->Use this time only" option results in two redirects with the discovery response back to the SP when using Firefox (4304)
> 
> 
> Using "Login and Use Forever->Yes I am Sure - Use Forever" only issues one redirect
> 
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Only ff?

**Comment by rebeckag** [comment]
Yup, neither Chrome or Safari does this. No idea about IE..

**Comment by leifj** [comment]
I'm going to close this issue since it is referring to code that is about to be deprecated and removed from pyFF. Work on the UX has moved to mdq-browser and theidentityselector/thiss-js for the admin ui and discovery service respectively.
