### ISSUE TITLE
role count per type

### ISSUE THREAD

**Issue by kevinfoote** [IdentityPython/pyFF#83]
Would be nice to have a count along with type for each: 

metadata by attributes >> role >> aa | sp | idp

No pull request at this time :( 
I'll try to find time to mock this up

**Comment by leifj** [comment]
I think I know what you're looking for and I've got an implementation for the memory store but I need to work on the redis version before I release this.

**Comment by leifj** [comment]
I'm going to close this issue since it is referring to code that is about to be deprecated and removed from pyFF. Work on the UX has moved to mdq-browser and theidentityselector/thiss-js for the admin ui and discovery service respectively.
