### ISSUE TITLE
Unclear ERROR message "Operation not permitted"

### ISSUE THREAD

**Issue by rhoerbe** [IdentityPython/pyFF#87]
I cannot explain the ERROR message in the context of this log:

```
DEBUG:root:importing builtins from pyff.pipes to find select
DEBUG:root:resolving /var/lib/git/pvmd/accepted filtered by //md:EntityDescriptor
DEBUG:root:string lookup /var/lib/git/pvmd/accepted
DEBUG:root:basic lookup /var/lib/git/pvmd/accepted
DEBUG:root:xpath filter //md:EntityDescriptor <- <Element {urn:oasis:names:tc:SAML:2.0:metadata}EntitiesDescriptor at 0x1500128>
DEBUG:root:selecting 1 entities from 1 entity set(s) before validation
DEBUG:root:importing builtins from pyff.pipes to find xslt
DEBUG:root:importing builtins from pyff.pipes to find store
ERROR:root:[Errno 1] Operation not permitted
DEBUG:root:importing builtins from pyff.pipes to find finalize
DEBUG:root:importing builtins from pyff.pipes to find sign
INFO:root:Attempting to extract certificate from token...
```

getenforce -> disabled

The pipeline is:

```
- load:
  - /var/lib/pyff/input
- select
- xslt:
    stylesheet: tidy.xsl
- store: 
     directory: /tmp/
- finalize:
     cacheDuration: PT4H
     validUntil: P10D
     ID: SignTestPortalverbundGvAt_
- sign:
    key: pkcs11:///usr/lib64/libeToken.so/test
- publish: /var/lib/git/pvmd/published/metadata_signed.xml
```

The output is correct, so this is not an immediate problem. But I have limited access to the customer's test system and will have to rely on the debug log once it is moved to production. More log data would increase my peace of mind:-)

**Comment by leifj** [comment]
so whats in that /tmp directory? any permission problems? what happens if you do store to /tmp/empty ?

**Comment by rhoerbe** [comment]
no problem, can do `touch /tmp/empty`

**Comment by leifj** [comment]
mkdir /tmp/empty ....

does that make the error go away?

**Comment by leifj** [comment]
also: can you do ls /tmp/empty after you run your pipeline once

**Comment by peppelinux** [comment]
Probably the problem could be the directory where .pid file Is written, by default It's /var/run but if pyffd Is run by a normal user (not root, suggested). I had also this problem, Yes this error message Is difficult to understand
