### ISSUE TITLE
IDP-disco: No indication of problem if selection cannot proceed

### ISSUE THREAD

**Issue by rhoerbe** [IdentityPython/pyFF#98]
If an IDP was selected and the javascript cannot continue for whatever reason, there is neither user feedback (the button does not react, however hard I click the mouse), nor a log file guiding the admin to the cause.

This happens e.g. with a request to https://ds.test.wpv.portalverbund.at/role/idp.ds?entityID=someValidEntityID&return=validReturnURL

or when running into issue #46

**Comment by leifj** [comment]
ok thats a good point. I'll think about how to render that feedback.

**Comment by leifj** [comment]
I'm going to close this issue since it is referring to code that is about to be deprecated and removed from pyFF. Work on the UX has moved to mdq-browser and theidentityselector/thiss-js for the admin ui and discovery service respectively.
